#include "GameData.h"

GameData game_data; // UUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUGHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH FINAAAAAAAAAALYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY // 4 freaking days to make a simple global variable